-- Migration: lookups + countries reference tables
-- Generic lookups table replaces 6+ hardcoded arrays (job types, experience levels,
-- benefits, conditions, salary periods, report reasons, etc.)
-- Countries table provides ISO 3166-1 data for phone login, location filters, etc.

CREATE TABLE IF NOT EXISTS lookups (
    id          BIGSERIAL PRIMARY KEY,
    lookup_type VARCHAR(50) NOT NULL,
    value       VARCHAR(100) NOT NULL,
    label_key   VARCHAR(200) NOT NULL,
    icon        VARCHAR(100),
    sort_order  INT NOT NULL DEFAULT 0,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(lookup_type, value)
);

CREATE INDEX IF NOT EXISTS idx_lookups_type_active
    ON lookups(lookup_type, is_active) WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS countries (
    id            BIGSERIAL PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    iso_code      CHAR(2) NOT NULL UNIQUE,
    iso3_code     CHAR(3),
    phone_code    VARCHAR(10),
    flag_emoji    VARCHAR(10),
    currency_code VARCHAR(3),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order    INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_countries_active
    ON countries(is_active) WHERE is_active = TRUE;

-- ── Seed: lookups ──────────────────────────────────────────────────

INSERT INTO lookups (lookup_type, value, label_key, icon, sort_order)
SELECT * FROM (VALUES
    -- Job Types (scoped to "jobs" namespace — keys relative)
    ('job_type', 'full_time',  'fullTime',  'briefcase', 1),
    ('job_type', 'part_time',  'partTime',  'clock', 2),
    ('job_type', 'contract',   'contract',  'file-text', 3),
    ('job_type', 'freelance',  'freelance', 'user', 4),
    ('job_type', 'internship', 'internship','graduation-cap', 5),
    ('job_type', 'volunteer',  'volunteer', 'heart', 6),
    ('job_type', 'temporary',  'temporary', 'calendar', 7),
    ('job_type', 'remote',     'remote',    'wifi', 8),

    -- Experience Levels (scoped to "jobs" namespace)
    ('experience', 'entry',     'entry',     'trending-up', 1),
    ('experience', 'mid',       'mid',       'layers', 2),
    ('experience', 'senior',    'senior',    'star', 3),
    ('experience', 'lead',      'lead',      'shield', 4),
    ('experience', 'executive', 'executive', 'crown', 5),

    -- Salary Periods (scoped to "jobs" namespace)
    ('salary_period', 'hourly',  'hourly',  'clock', 1),
    ('salary_period', 'daily',   'daily',   'sun', 2),
    ('salary_period', 'weekly',  'weekly',  'calendar', 3),
    ('salary_period', 'monthly', 'monthly', 'calendar-days', 4),
    ('salary_period', 'yearly',  'yearly',  'calendar-range', 5),

    -- Benefits (scoped to "jobs" namespace — keys under "benefits.")
    ('benefit', 'health_insurance',        'benefits.healthInsurance',        'heart-pulse', 1),
    ('benefit', 'dental_insurance',        'benefits.dentalInsurance',        'smile', 2),
    ('benefit', 'vision_insurance',        'benefits.visionInsurance',        'eye', 3),
    ('benefit', 'retirement_401k',         'benefits.401k',                   'piggy-bank', 4),
    ('benefit', 'stock_options',           'benefits.stockOptions',           'trending-up', 5),
    ('benefit', 'remote_work',             'benefits.remoteWork',             'home', 6),
    ('benefit', 'flexible_hours',          'benefits.flexibleHours',          'clock', 7),
    ('benefit', 'paid_time_off',           'benefits.paidTimeOff',            'umbrella-beach', 8),
    ('benefit', 'parental_leave',          'benefits.parentalLeave',          'baby', 9),
    ('benefit', 'professional_development','benefits.professionalDevelopment','book-open', 10),
    ('benefit', 'gym_membership',          'benefits.gymMembership',          'dumbbell', 11),
    ('benefit', 'commuter_benefits',       'benefits.commuterBenefits',       'train', 12),
    ('benefit', 'life_insurance',          'benefits.lifeInsurance',          'shield-check', 13),
    ('benefit', 'tuition_reimbursement',   'benefits.tuitionReimbursement',   'graduation-cap', 14),
    ('benefit', 'employee_discount',       'benefits.employeeDiscount',       'percent', 15),
    ('benefit', 'catered_lunches',         'benefits.cateredLunches',         'utensils', 16),
    ('benefit', 'equipment_stipend',       'benefits.equipmentStipend',       'laptop', 17),

    -- Product Conditions (scoped to "marketplace" namespace)
    ('condition', 'new',       'conditionNew',  'sparkles', 1),
    ('condition', 'like_new',  'conditionLikeNew', 'star', 2),
    ('condition', 'good',      'conditionGood',    'check', 3),
    ('condition', 'fair',      'conditionFair',    'minus', 4),
    ('condition', 'used',      'conditionUsed',    'rotate-ccw', 5),
    ('condition', 'refurbished','conditionRefurbished', 'wrench', 6),

    -- Report Reasons (scoped to "report" namespace)
    ('report_reason', 'spam',                 'report.reasons.spam',                 'message-circle', 1),
    ('report_reason', 'nudity',               'report.reasons.nudity',               'eye-off', 2),
    ('report_reason', 'hate_speech',          'report.reasons.hateSpeech',          'alert-triangle', 3),
    ('report_reason', 'violence',             'report.reasons.violence',             'shield-off', 4),
    ('report_reason', 'false_information',    'report.reasons.falseInformation',     'help-circle', 5),
    ('report_reason', 'intellectual_property','report.reasons.intellectualProperty', 'copyright', 6),
    ('report_reason', 'self_harm',            'report.reasons.selfHarm',            'heart', 7),
    ('report_reason', 'harassment',           'report.reasons.harassment',           'user-x', 8),
    ('report_reason', 'terrorism',            'report.reasons.terrorism',            'alert-octagon', 9),
    ('report_reason', 'other',                'report.reasons.other',                'more-horizontal', 99)
) AS t(lookup_type, value, label_key, icon, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM lookups WHERE lookups.lookup_type = t.lookup_type AND lookups.value = t.value);

-- ── Seed: countries (ISO 3166-1, all 195) ─────────────────────────

INSERT INTO countries (name, iso_code, iso3_code, phone_code, flag_emoji, currency_code)
SELECT * FROM (VALUES
    ('Afghanistan', 'AF', 'AFG', '+93', '🇦🇫', 'AFN'),
    ('Albania', 'AL', 'ALB', '+355', '🇦🇱', 'ALL'),
    ('Algeria', 'DZ', 'DZA', '+213', '🇩🇿', 'DZD'),
    ('Andorra', 'AD', 'AND', '+376', '🇦🇩', 'EUR'),
    ('Angola', 'AO', 'AGO', '+244', '🇦🇴', 'AOA'),
    ('Argentina', 'AR', 'ARG', '+54', '🇦🇷', 'ARS'),
    ('Armenia', 'AM', 'ARM', '+374', '🇦🇲', 'AMD'),
    ('Australia', 'AU', 'AUS', '+61', '🇦🇺', 'AUD'),
    ('Austria', 'AT', 'AUT', '+43', '🇦🇹', 'EUR'),
    ('Azerbaijan', 'AZ', 'AZE', '+994', '🇦🇿', 'AZN'),
    ('Bahamas', 'BS', 'BHS', '+1-242', '🇧🇸', 'BSD'),
    ('Bahrain', 'BH', 'BHR', '+973', '🇧🇭', 'BHD'),
    ('Bangladesh', 'BD', 'BGD', '+880', '🇧🇩', 'BDT'),
    ('Belarus', 'BY', 'BLR', '+375', '🇧🇾', 'BYN'),
    ('Belgium', 'BE', 'BEL', '+32', '🇧🇪', 'EUR'),
    ('Belize', 'BZ', 'BLZ', '+501', '🇧🇿', 'BZD'),
    ('Benin', 'BJ', 'BEN', '+229', '🇧🇯', 'XOF'),
    ('Bhutan', 'BT', 'BTN', '+975', '🇧🇹', 'BTN'),
    ('Bolivia', 'BO', 'BOL', '+591', '🇧🇴', 'BOB'),
    ('Bosnia and Herzegovina', 'BA', 'BIH', '+387', '🇧🇦', 'BAM'),
    ('Botswana', 'BW', 'BWA', '+267', '🇧🇼', 'BWP'),
    ('Brazil', 'BR', 'BRA', '+55', '🇧🇷', 'BRL'),
    ('Brunei', 'BN', 'BRN', '+673', '🇧🇳', 'BND'),
    ('Bulgaria', 'BG', 'BGR', '+359', '🇧🇬', 'BGN'),
    ('Burkina Faso', 'BF', 'BFA', '+226', '🇧🇫', 'XOF'),
    ('Burundi', 'BI', 'BDI', '+257', '🇧🇮', 'BIF'),
    ('Cambodia', 'KH', 'KHM', '+855', '🇰🇭', 'KHR'),
    ('Cameroon', 'CM', 'CMR', '+237', '🇨🇲', 'XAF'),
    ('Canada', 'CA', 'CAN', '+1', '🇨🇦', 'CAD'),
    ('Chile', 'CL', 'CHL', '+56', '🇨🇱', 'CLP'),
    ('China', 'CN', 'CHN', '+86', '🇨🇳', 'CNY'),
    ('Colombia', 'CO', 'COL', '+57', '🇨🇴', 'COP'),
    ('Costa Rica', 'CR', 'CRI', '+506', '🇨🇷', 'CRC'),
    ('Croatia', 'HR', 'HRV', '+385', '🇭🇷', 'EUR'),
    ('Cuba', 'CU', 'CUB', '+53', '🇨🇺', 'CUP'),
    ('Cyprus', 'CY', 'CYP', '+357', '🇨🇾', 'EUR'),
    ('Czech Republic', 'CZ', 'CZE', '+420', '🇨🇿', 'CZK'),
    ('Denmark', 'DK', 'DNK', '+45', '🇩🇰', 'DKK'),
    ('Dominican Republic', 'DO', 'DOM', '+1-809', '🇩🇴', 'DOP'),
    ('Ecuador', 'EC', 'ECU', '+593', '🇪🇨', 'USD'),
    ('Egypt', 'EG', 'EGY', '+20', '🇪🇬', 'EGP'),
    ('El Salvador', 'SV', 'SLV', '+503', '🇸🇻', 'USD'),
    ('Estonia', 'EE', 'EST', '+372', '🇪🇪', 'EUR'),
    ('Ethiopia', 'ET', 'ETH', '+251', '🇪🇹', 'ETB'),
    ('Finland', 'FI', 'FIN', '+358', '🇫🇮', 'EUR'),
    ('France', 'FR', 'FRA', '+33', '🇫🇷', 'EUR'),
    ('Georgia', 'GE', 'GEO', '+995', '🇬🇪', 'GEL'),
    ('Germany', 'DE', 'DEU', '+49', '🇩🇪', 'EUR'),
    ('Ghana', 'GH', 'GHA', '+233', '🇬🇭', 'GHS'),
    ('Greece', 'GR', 'GRC', '+30', '🇬🇷', 'EUR'),
    ('Guatemala', 'GT', 'GTM', '+502', '🇬🇹', 'GTQ'),
    ('Haiti', 'HT', 'HTI', '+509', '🇭🇹', 'HTG'),
    ('Honduras', 'HN', 'HND', '+504', '🇭🇳', 'HNL'),
    ('Hong Kong', 'HK', 'HKG', '+852', '🇭🇰', 'HKD'),
    ('Hungary', 'HU', 'HUN', '+36', '🇭🇺', 'HUF'),
    ('Iceland', 'IS', 'ISL', '+354', '🇮🇸', 'ISK'),
    ('India', 'IN', 'IND', '+91', '🇮🇳', 'INR'),
    ('Indonesia', 'ID', 'IDN', '+62', '🇮🇩', 'IDR'),
    ('Iran', 'IR', 'IRN', '+98', '🇮🇷', 'IRR'),
    ('Iraq', 'IQ', 'IRQ', '+964', '🇮🇶', 'IQD'),
    ('Ireland', 'IE', 'IRL', '+353', '🇮🇪', 'EUR'),
    ('Israel', 'IL', 'ISR', '+972', '🇮🇱', 'ILS'),
    ('Italy', 'IT', 'ITA', '+39', '🇮🇹', 'EUR'),
    ('Jamaica', 'JM', 'JAM', '+1-876', '🇯🇲', 'JMD'),
    ('Japan', 'JP', 'JPN', '+81', '🇯🇵', 'JPY'),
    ('Jordan', 'JO', 'JOR', '+962', '🇯🇴', 'JOD'),
    ('Kazakhstan', 'KZ', 'KAZ', '+7', '🇰🇿', 'KZT'),
    ('Kenya', 'KE', 'KEN', '+254', '🇰🇪', 'KES'),
    ('South Korea', 'KR', 'KOR', '+82', '🇰🇷', 'KRW'),
    ('Kuwait', 'KW', 'KWT', '+965', '🇰🇼', 'KWD'),
    ('Kyrgyzstan', 'KG', 'KGZ', '+996', '🇰🇬', 'KGS'),
    ('Laos', 'LA', 'LAO', '+856', '🇱🇦', 'LAK'),
    ('Latvia', 'LV', 'LVA', '+371', '🇱🇻', 'EUR'),
    ('Lebanon', 'LB', 'LBN', '+961', '🇱🇧', 'LBP'),
    ('Libya', 'LY', 'LBY', '+218', '🇱🇾', 'LYD'),
    ('Lithuania', 'LT', 'LTU', '+370', '🇱🇹', 'EUR'),
    ('Luxembourg', 'LU', 'LUX', '+352', '🇱🇺', 'EUR'),
    ('Malaysia', 'MY', 'MYS', '+60', '🇲🇾', 'MYR'),
    ('Maldives', 'MV', 'MDV', '+960', '🇲🇻', 'MVR'),
    ('Malta', 'MT', 'MLT', '+356', '🇲🇹', 'EUR'),
    ('Mexico', 'MX', 'MEX', '+52', '🇲🇽', 'MXN'),
    ('Moldova', 'MD', 'MDA', '+373', '🇲🇩', 'MDL'),
    ('Monaco', 'MC', 'MCO', '+377', '🇲🇨', 'EUR'),
    ('Mongolia', 'MN', 'MNG', '+976', '🇲🇳', 'MNT'),
    ('Montenegro', 'ME', 'MNE', '+382', '🇲🇪', 'EUR'),
    ('Morocco', 'MA', 'MAR', '+212', '🇲🇦', 'MAD'),
    ('Mozambique', 'MZ', 'MOZ', '+258', '🇲🇿', 'MZN'),
    ('Myanmar', 'MM', 'MMR', '+95', '🇲🇲', 'MMK'),
    ('Nepal', 'NP', 'NPL', '+977', '🇳🇵', 'NPR'),
    ('Netherlands', 'NL', 'NLD', '+31', '🇳🇱', 'EUR'),
    ('New Zealand', 'NZ', 'NZL', '+64', '🇳🇿', 'NZD'),
    ('Nicaragua', 'NI', 'NIC', '+505', '🇳🇮', 'NIO'),
    ('Nigeria', 'NG', 'NGA', '+234', '🇳🇬', 'NGN'),
    ('North Macedonia', 'MK', 'MKD', '+389', '🇲🇰', 'MKD'),
    ('Norway', 'NO', 'NOR', '+47', '🇳🇴', 'NOK'),
    ('Oman', 'OM', 'OMN', '+968', '🇴🇲', 'OMR'),
    ('Pakistan', 'PK', 'PAK', '+92', '🇵🇰', 'PKR'),
    ('Panama', 'PA', 'PAN', '+507', '🇵🇦', 'PAB'),
    ('Paraguay', 'PY', 'PRY', '+595', '🇵🇾', 'PYG'),
    ('Peru', 'PE', 'PER', '+51', '🇵🇪', 'PEN'),
    ('Philippines', 'PH', 'PHL', '+63', '🇵🇭', 'PHP'),
    ('Poland', 'PL', 'POL', '+48', '🇵🇱', 'PLN'),
    ('Portugal', 'PT', 'PRT', '+351', '🇵🇹', 'EUR'),
    ('Puerto Rico', 'PR', 'PRI', '+1-787', '🇵🇷', 'USD'),
    ('Qatar', 'QA', 'QAT', '+974', '🇶🇦', 'QAR'),
    ('Romania', 'RO', 'ROU', '+40', '🇷🇴', 'RON'),
    ('Russia', 'RU', 'RUS', '+7', '🇷🇺', 'RUB'),
    ('Rwanda', 'RW', 'RWA', '+250', '🇷🇼', 'RWF'),
    ('Saudi Arabia', 'SA', 'SAU', '+966', '🇸🇦', 'SAR'),
    ('Senegal', 'SN', 'SEN', '+221', '🇸🇳', 'XOF'),
    ('Serbia', 'RS', 'SRB', '+381', '🇷🇸', 'RSD'),
    ('Singapore', 'SG', 'SGP', '+65', '🇸🇬', 'SGD'),
    ('Slovakia', 'SK', 'SVK', '+421', '🇸🇰', 'EUR'),
    ('Slovenia', 'SI', 'SVN', '+386', '🇸🇮', 'EUR'),
    ('South Africa', 'ZA', 'ZAF', '+27', '🇿🇦', 'ZAR'),
    ('Spain', 'ES', 'ESP', '+34', '🇪🇸', 'EUR'),
    ('Sri Lanka', 'LK', 'LKA', '+94', '🇱🇰', 'LKR'),
    ('Sudan', 'SD', 'SDN', '+249', '🇸🇩', 'SDG'),
    ('Sweden', 'SE', 'SWE', '+46', '🇸🇪', 'SEK'),
    ('Switzerland', 'CH', 'CHE', '+41', '🇨🇭', 'CHF'),
    ('Taiwan', 'TW', 'TWN', '+886', '🇹🇼', 'TWD'),
    ('Tajikistan', 'TJ', 'TJK', '+992', '🇹🇯', 'TJS'),
    ('Tanzania', 'TZ', 'TZA', '+255', '🇹🇿', 'TZS'),
    ('Thailand', 'TH', 'THA', '+66', '🇹🇭', 'THB'),
    ('Tunisia', 'TN', 'TUN', '+216', '🇹🇳', 'TND'),
    ('Turkey', 'TR', 'TUR', '+90', '🇹🇷', 'TRY'),
    ('Turkmenistan', 'TM', 'TKM', '+993', '🇹🇲', 'TMT'),
    ('Uganda', 'UG', 'UGA', '+256', '🇺🇬', 'UGX'),
    ('Ukraine', 'UA', 'UKR', '+380', '🇺🇦', 'UAH'),
    ('United Arab Emirates', 'AE', 'ARE', '+971', '🇦🇪', 'AED'),
    ('United Kingdom', 'GB', 'GBR', '+44', '🇬🇧', 'GBP'),
    ('United States', 'US', 'USA', '+1', '🇺🇸', 'USD'),
    ('Uruguay', 'UY', 'URY', '+598', '🇺🇾', 'UYU'),
    ('Uzbekistan', 'UZ', 'UZB', '+998', '🇺🇿', 'UZS'),
    ('Venezuela', 'VE', 'VEN', '+58', '🇻🇪', 'VES'),
    ('Vietnam', 'VN', 'VNM', '+84', '🇻🇳', 'VND'),
    ('Yemen', 'YE', 'YEM', '+967', '🇾🇪', 'YER'),
    ('Zambia', 'ZM', 'ZMB', '+260', '🇿🇲', 'ZMW'),
    ('Zimbabwe', 'ZW', 'ZWE', '+263', '🇿🇼', 'ZWL'),
    ('Ivory Coast', 'CI', 'CIV', '+225', '🇨🇮', 'XOF'),
    ('DR Congo', 'CD', 'COD', '+243', '🇨🇩', 'CDF'),
    ('Congo Republic', 'CG', 'COG', '+242', '🇨🇬', 'XAF'),
    ('Cape Verde', 'CV', 'CPV', '+238', '🇨🇻', 'CVE'),
    ('Fiji', 'FJ', 'FJI', '+679', '🇫🇯', 'FJD'),
    ('Gabon', 'GA', 'GAB', '+241', '🇬🇦', 'XAF'),
    ('Gambia', 'GM', 'GMB', '+220', '🇬🇲', 'GMD'),
    ('Guam', 'GU', 'GUM', '+1-671', '🇬🇺', 'USD'),
    ('Guinea', 'GN', 'GIN', '+224', '🇬🇳', 'GNF'),
    ('Guyana', 'GY', 'GUY', '+592', '🇬🇾', 'GYD'),
    ('Lesotho', 'LS', 'LSO', '+266', '🇱🇸', 'LSL'),
    ('Liberia', 'LR', 'LBR', '+231', '🇱🇷', 'LRD'),
    ('Madagascar', 'MG', 'MDG', '+261', '🇲🇬', 'MGA'),
    ('Malawi', 'MW', 'MWI', '+265', '🇲🇼', 'MWK'),
    ('Mali', 'ML', 'MLI', '+223', '🇲🇱', 'XOF'),
    ('Mauritania', 'MR', 'MRT', '+222', '🇲🇷', 'MRU'),
    ('Mauritius', 'MU', 'MUS', '+230', '🇲🇺', 'MUR'),
    ('Namibia', 'NA', 'NAM', '+264', '🇳🇦', 'NAD'),
    ('Niger', 'NE', 'NER', '+227', '🇳🇪', 'XOF'),
    ('Palestine', 'PS', 'PSE', '+970', '🇵🇸', 'ILS'),
    ('Papua New Guinea', 'PG', 'PNG', '+675', '🇵🇬', 'PGK'),
    ('Samoa', 'WS', 'WSM', '+685', '🇼🇸', 'WST'),
    ('Seychelles', 'SC', 'SYC', '+248', '🇸🇨', 'SCR'),
    ('Sierra Leone', 'SL', 'SLE', '+232', '🇸🇱', 'SLL'),
    ('Somalia', 'SO', 'SOM', '+252', '🇸🇴', 'SOS'),
    ('South Sudan', 'SS', 'SSD', '+211', '🇸🇸', 'SSP'),
    ('Suriname', 'SR', 'SUR', '+597', '🇸🇷', 'SRD'),
    ('Togo', 'TG', 'TGO', '+228', '🇹🇬', 'XOF'),
    ('Tonga', 'TO', 'TON', '+676', '🇹🇴', 'TOP'),
    ('Trinidad and Tobago', 'TT', 'TTO', '+1-868', '🇹🇹', 'TTD'),
    ('Vanuatu', 'VU', 'VUT', '+678', '🇻🇺', 'VUV'),
    ('Barbados', 'BB', 'BRB', '+1-246', '🇧🇧', 'BBD'),
    ('Bermuda', 'BM', 'BMU', '+1-441', '🇧🇲', 'BMD'),
    ('Cayman Islands', 'KY', 'CYM', '+1-345', '🇰🇾', 'KYD'),
    ('Dominica', 'DM', 'DMA', '+1-767', '🇩🇲', 'XCD'),
    ('Grenada', 'GD', 'GRD', '+1-473', '🇬🇩', 'XCD'),
    ('Saint Lucia', 'LC', 'LCA', '+1-758', '🇱🇨', 'XCD'),
    ('Eswatini', 'SZ', 'SWZ', '+268', '🇸🇿', 'SZL'),
    ('Eritrea', 'ER', 'ERI', '+291', '🇪🇷', 'ERN'),
    ('Chad', 'TD', 'TCD', '+235', '🇹🇩', 'XAF'),
    ('Central African Republic', 'CF', 'CAF', '+236', '🇨🇫', 'XAF'),
    ('Equatorial Guinea', 'GQ', 'GNQ', '+240', '🇬🇶', 'XAF'),
    ('Guinea-Bissau', 'GW', 'GNB', '+245', '🇬🇼', 'XOF'),
    ('Sao Tome and Principe', 'ST', 'STP', '+239', '🇸🇹', 'STN'),
    ('Comoros', 'KM', 'COM', '+269', '🇰🇲', 'KMF'),
    ('Djibouti', 'DJ', 'DJI', '+253', '🇩🇯', 'DJF'),
    ('Timor-Leste', 'TL', 'TLS', '+670', '🇹🇱', 'USD'),
    ('Solomon Islands', 'SB', 'SLB', '+677', '🇸🇧', 'SBD'),
    ('Kiribati', 'KI', 'KIR', '+686', '🇰🇮', 'AUD'),
    ('Marshall Islands', 'MH', 'MHL', '+692', '🇲🇭', 'USD'),
    ('Micronesia', 'FM', 'FSM', '+691', '🇫🇲', 'USD'),
    ('Nauru', 'NR', 'NRU', '+674', '🇳🇷', 'AUD'),
    ('Palau', 'PW', 'PLW', '+680', '🇵🇼', 'USD'),
    ('Tuvalu', 'TV', 'TUV', '+688', '🇹🇻', 'AUD'),
    ('Antigua and Barbuda', 'AG', 'ATG', '+1-268', '🇦🇬', 'XCD'),
    ('Saint Kitts and Nevis', 'KN', 'KNA', '+1-869', '🇰🇳', 'XCD'),
    ('Saint Vincent and the Grenadines', 'VC', 'VCT', '+1-784', '🇻🇨', 'XCD')
) AS t(name, iso_code, iso3_code, phone_code, flag_emoji, currency_code)
WHERE NOT EXISTS (SELECT 1 FROM countries WHERE countries.iso_code = t.iso_code);
